# Generated by Django 2.2.16 on 2022-12-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221206_1445'),
        ('users', '0002_auto_20221206_2151'),
    ]

    operations = [
    ]
