# Generated by Django 2.2.16 on 2022-12-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20221207_1642'),
        ('users', '0003_merge_20221207_1744'),
    ]

    operations = [
    ]
