# Generated by Django 2.2.16 on 2022-11-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=256, verbose_name='Имя')),
                ('slug', models.SlugField(help_text='Адрес категории', unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Категория произведения',
                'verbose_name_plural': 'Категории произведений',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название жанра', max_length=256, verbose_name='Имя')),
                ('slug', models.SlugField(help_text='Адрес жанра', unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произведение', max_length=256, verbose_name='Имя')),
                ('year', models.DateField(help_text='Год выпуска', verbose_name='Год выпуска')),
                ('description', models.TextField(help_text='Описание', verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Категория', on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='reviews.Categories', verbose_name='Категория')),
                ('genre', models.ForeignKey(help_text='Жанр', on_delete=django.db.models.deletion.DO_NOTHING, related_name='genres', to='reviews.Genres', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
        migrations.CreateModel(
            name='GenresOfTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(help_text='Жанр', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Genres', verbose_name='Жанр')),
                ('title', models.ForeignKey(help_text='Произведения', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='reviews.Titles', verbose_name='Произведения')),
            ],
            options={
                'verbose_name': 'Жанры произведения',
                'verbose_name_plural': 'Жанры произведения',
                'ordering': ['title', 'genre'],
            },
        ),
        migrations.AddConstraint(
            model_name='genresoftitles',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='title_genre'),
        ),
    ]
