# Generated by Django 2.2.16 on 2022-12-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.ForeignKey(help_text='Произведение', on_delete=django.db.models.deletion.CASCADE, to='reviews.Title', verbose_name='Произведение'),
        ),
        migrations.AddField(
            model_name='genresoftitles',
            name='genre',
            field=models.ForeignKey(help_text='Жанр', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='genresoftitles',
            name='title',
            field=models.ForeignKey(help_text='Произведение', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='reviews.Title', verbose_name='Произведение'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(help_text='Отзыв', on_delete=django.db.models.deletion.CASCADE, to='reviews.Review', verbose_name='Отзыв'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_review'),
        ),
        migrations.AddConstraint(
            model_name='genresoftitles',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='title_genre'),
        ),
    ]
