# Generated by Django 2.2.16 on 2022-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Адрес категории', verbose_name='Адрес'),
        ),
    ]
