# Generated by Django 2.2.16 on 2022-12-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221206_2255'),
        ('reviews', '0005_auto_20221206_1527'),
    ]

    operations = [
    ]
